# This is a basic workflow to help you get started with Actions

name: Test PR

on: 
  pull_request:
    types:
      - closed
    branches:
      - pr1

env:
  name: 'sai'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: check service name
        run: |
          if [[ $name == 'Sai' ]]; then
            echo "Start Job"
          fi
      
      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: ech Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
  deploy:
    if: $name == 'Sai'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hi, Sai Naveen Akula"
